AWSTemplateFormatVersion: '2010-09-09'
Description: Free-tier MySQL RDS instance with credentials in Secrets Manager

Parameters:
  DBUsername:
    Description: Master database username
    Type: String
    Default: admin
  DBPassword:
    Description: Master database password (min 8 chars)
    Type: String
    NoEcho: true
    MinLength: 8


Resources:
  # Only create new secret if ExistingSecretName is not provided
  MyDBSecret:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Name: db-secret
      Description: RDS credentials for MySQL
      SecretString: !Sub |
        {
          "username": "${DBUsername}",
          "password": "${DBPassword}"
        }


  MyDBInstance:
    Type: AWS::RDS::DBInstance
    UpdateReplacePolicy: Delete
    Properties:
      DBInstanceIdentifier: demo-db
      DBInstanceClass: db.t3.micro
      AllocatedStorage: 20
      Engine: mysql
      EngineVersion: 8.0.35
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      PubliclyAccessible: false
      BackupRetentionPeriod: 0
      DBName: myappdb
      DeletionProtection: false
      StorageType: gp2
      MultiAZ: false
      VPCSecurityGroups:
        - !GetAtt MyDBSecurityGroup.GroupId
      DBSubnetGroupName: !Ref MyDBSubnetGroup

  RDSDNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: Z05736022TWK3R2C91ZQB
      Name: rds.tonythomasm.com
      Type: CNAME
      TTL: 60
      ResourceRecords:
        - !GetAtt MyDBInstance.Endpoint.Address

  MyDBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow RDS access
      VpcId: !ImportValue VPC  
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !ImportValue InstanceSecurityGroup
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !ImportValue BastionHostSecurityGroupId

  MyDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnets for RDS
      SubnetIds:
        - !ImportValue PrivateSubnet1
        - !ImportValue PrivateSubnet2
        - !ImportValue PrivateSubnet3

Outputs:
  RDSInstanceEndpoint:
    Description: RDS endpoint URL
    Value: !GetAtt MyDBInstance.Endpoint.Address
    Export:
      Name: MyRDSInstanceEndpoint

  RDSSecretArn:
    Description: ARN of the Secrets Manager secret
    Value: !Ref MyDBSecret
    Export:
      Name: MyRDSSecretArn